export const categoryIcons: Record<string, string> = {
  Moradia: '🏠',
  Alimentação: '🍔',
  Transporte: '🚗',
  Lazer: '🎉',
  Saúde: '💊',
  Outros: '📦',
  Salário: '💸',
  Educação: '📚',
  Vestuário: '👕',
  Pets: '🐕',
  Investimentos: '📈',
  Manutenção: '🔨',
  Supermercado: '🛒',
  Carro: '🚗',
  Academia: '🏋️‍♂️',
  Presente: '🎁',
  Assinaturas: '🎥',
};
